### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by khurramharoon** [kgb1001001/cloudadoptionpatterns#1]
I found following typos so far as I am reading.
1) Introduction page (https://kgb1001001.github.io/cloudadoptionpatterns/)
a) Cloud Adoption
typo: **applciations** toward a cloud-native approach
b) Cloud Client Architecture
typo:  **faciliatate** cloud-native development.

2) Cloud Centric Design (https://kgb1001001.github.io/cloudadoptionpatterns/Cloud-Adoption/Cloud-Centric-Design.html)
Towards last third of the page
a) typo: Minimizing the use of state (it is impossible to entirely eliminate state, but you should **ony** keep the state that is absolutely required).
b) typo: It would take advantage of Scaleable Stores that allow development teams to match the data **stroage** technology to the type of data that being stored and to the data storage and retrieval patterns that are most prevalent for that application

3) Implement Monolith First (https://kgb1001001.github.io/cloudadoptionpatterns/Cloud-Adoption/Implement-Monolith-First.html)
8th paragraph
typo: because the right way is simply not known at this stage: when the application is not **successul**, the right decision is to shut it down, not to rearchitect it into something more beautiful

4) Lift and Shift (https://kgb1001001.github.io/cloudadoptionpatterns/Cloud-Adoption/Lift-and-Shift.html)
a) 5th paragraph
typo: There are three basic steps that you need to ensure in order **ot** make a Lift and Shift possible.
b) bullet point #2
typo: In many cases, even if the **applciation** runs entirely in the cloud, all requests to the application must come up through a direct connection to a corporate internet
c) bullet point #3
requirements or **dependinces** on databases that are shared across many applications may require the latter
d) second last paragraph
typo: apply to traditional application **resiliancy** as well, although the implementation choices may differ on which technologies you choose to perform data replication

As I continue my reading, I will keep taking notes and share it as an open issue.

Regards:
--kh

**Comment by kgb1001001** [comment]
Thanks Khurram!  We've addressed all of the typos in this issue
