### ISSUE TITLE
Some image links broken

### ISSUE THREAD

**Issue by ijmitch** [kgb1001001/cloudadoptionpatterns#12]
For example on https://kgb1001001.github.io/cloudadoptionpatterns/Strangler-Patterns/ .

Seems like there's a problem with the use of `<img>` in finding the `.png`s. Reverting Markdown `![blah](imagepath)` works.

**Comment by ijmitch** [comment]
it's misleading that the images appear when the file is rendered in github (as source) but not when Pages has built it.

**Comment by ijmitch** [comment]
@yodamann I think you're better off dumping the `<img>` tag for images and using Markdown - Jekyll isn't like them. I did try a few attempts to get `<img>` to work in my fork but nothing fixed it once the Pages build got hold of it.

**Comment by ijmitch** [comment]
I experimented with another Jekyll site trying both `<img>` and `![]()` forms for images... I found that the `src=` needed an extra set of `../` compared to the path in `![]()` (even though both resolved in the source preview).

**Comment by kgb1001001** [comment]
No longer an issue after the merge.
