### ISSUE TITLE
few more typos

### ISSUE THREAD

**Issue by khurramharoon** [kgb1001001/cloudadoptionpatterns#2]
Hi:
A few more typos to report.  

1) Look For Hairline Cracks (https://kgb1001001.github.io/cloudadoptionpatterns/Cloud-Adoption/Look-For-Hairline-Cracks.html)
a) first paragraph:
in order to improve the **maintainance** of the application and to reduce the blast radius of new changes to the application 
2) Identify Entities and Aggregates
(https://kgb1001001.github.io/cloudadoptionpatterns/Cloud-Native-Architecture/Identify-Entities-And-Aggregates.html)
a) 6th paragraph 
Typo: Entities also have attributes that might change, but the identifier for the **person** stays the same. 
Correction: Entities also have attributes that might change, but the identifier for the **entity** stays the same. 
b) second last paragraph: They often form the boundaries of **transactionality**.
3) Identify Domain Events (https://kgb1001001.github.io/cloudadoptionpatterns/Cloud-Native-Architecture/Identify-Domain-Events.html)
a) 7th paragraph:  
These facts are now Events in that they show how one **occurance** will be followed in time by another and another and another.
4) Event Driven Architecture (https://kgb1001001.github.io/cloudadoptionpatterns/Event-Based-Architecture/Event-Driven-Architecture.html)
last paragraph
Typo: An Event-Driven Architecture extends loose coupling to event coupling in which because the targets are optional; **the source announces the occurrence the same** whether the announcement goes to no, one, or multiple targets. It enables each target to receive the notification and decide how to react, if at all, such as which service to invoke.
Correction: An Event-Driven Architecture extends loose coupling to event coupling in which because the targets are optional; **the source announces the occurrence the same way** whether the announcement goes to no, one, or multiple targets. It enables each target to receive the notification and decide how to react, if at all, such as which service to invoke.
5) Service Mesh
3rd paragraph: Even performance management becomes more challenging to implement, because instead of calls that are fixed in time, you have the **vagaraties** of network communication added into the mix.

**Comment by kgb1001001** [comment]
All fixed except number 5, which I could not because the word is spelled correctly as is.  Thanks!
