### ISSUE TITLE
mostly typos

### ISSUE THREAD

**Issue by khurramharoon** [kgb1001001/cloudadoptionpatterns#3]
1) Adapter microservices(https://kgb1001001.github.io/cloudadoptionpatterns/Microservices/Adapter-Microservice.html)
a)3rd paragraph: Or it may be that you want to take advantage of a cloud-based (SaaS) API from a **clodu** provider that provides some or most of the functionality that you would otherwise have to build.
2) Page Cache (https://kgb1001001.github.io/cloudadoptionpatterns/Microservices/Page-Cache.html)
a) Broken page reference in first paragraph: You are building a web or mobile application using a Microservices Architecture**]**(**Microservices-Architecture.md**)
3) Event Based Architecture(https://kgb1001001.github.io/cloudadoptionpatterns/Event-Based-Architecture)
a) Issue: The link and the page title do not match.  Link states **Event Based Architecture** and the corresponding page title states **Event Driven Architecture**.
4) Event Sourcing (https://kgb1001001.github.io/cloudadoptionpatterns/Event-Based-Architecture/Event-Sourcing.html)
a) Ist paragraph: When you are designing applications that use Events you often find that the approach of **repseenting** the state of your application
b) 2nd paragraph: **Waht’s** more, it’s also hard to figure out the logic of how to “undo” things when conditions change.

**Comment by kgb1001001** [comment]
Addressed all typos and broken links.  Thanks Khurram!
