### ISSUE TITLE
New pattern: Container Orchestrator

### ISSUE THREAD

**Issue by bwoolf1** [kgb1001001/cloudadoptionpatterns#4]
Add a pattern on container orchestration.

**Comment by kgb1001001** [comment]
What would you think about moving this pattern from its current position (in the poorly-named "container-architecture") to the section "Cloud-Native-Architecture".  That section is more of a grab-bag of top-level architectural patterns, whereas the other section has become much more specialized to container devops.

**Comment by bwoolf1** [comment]
Good idea. https://github.com/bwoolf1/cloudadoptionpatterns/commit/f407be9b84e8bed1da05decdf625360fd2f717d4 moves the file to the "Cloud Native Architecture" section. https://github.com/bwoolf1/cloudadoptionpatterns/commit/5e1ebd6ec33461a0aef828bb9ab7746a48c8e408 updates the links.

**Comment by kgb1001001** [comment]
Merged and done.  I'll add it into the navigation.
